targets:
  $default:
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: true
      build_web_compilers:entrypoint:
        enabled: false
  debug:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/workers/*.debug.dart
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
  release:
    auto_apply_builders: false
    builders:
      build_web_compilers:dart2js_archive_extractor:
        enabled: false
      build_web_compilers:entrypoint:
        enabled: true
        generate_for:
          - lib/workers/*.release.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O2
            - --define=dart.vm.product=true
  workers:
    auto_apply_builders: false
    builders:
      worker_bee_builder:worker_copy_builder:
        enabled: true
        generate_for:
          - lib/workers/*.debug.dart.js
          - lib/workers/*.debug.dart.js.map
          - lib/workers/*.release.dart.js
          - lib/workers/*.release.dart.js.map
    dependencies:
      - coffee:debug
      - coffee:release
