name: coffee
description: An app for browsing and cataloging your favorite coffees.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  amplify_db_common_dart: ^0.1.1
  async: ^2.9.0
  aws_common: ^0.3.5+1
  built_collection: ^5.1.1
  built_value: ^8.4.3
  drift: ^2.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  image: ^3.0.0
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.0
  riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  sqlite3_flutter_libs: ^0.5.0
  worker_bee: ^0.1.3+1

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  built_value_generator: ^8.4.3
  drift_dev: ^2.4.1
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_generator: ^1.1.1
  worker_bee_builder: ^0.1.4+1

flutter:
  uses-material-design: true
  assets:
    - lib/workers/workers.js
    - lib/workers/workers.min.js

flutter_icons:
  image_path: "icon.png"
  android: "launcher_icon"
  ios: true
  web:
    generate: true
    background_color: "#DCBAA3"
    theme_color: "#6F4E37"
  macos:
    generate: true
